/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.university.course.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Course service. Represents a row in the &quot;CollegeCourse_Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.university.course.model.impl.CourseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.university.course.model.impl.CourseImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Course
 * @generated
 */
@ProviderType
public interface CourseModel extends BaseModel<Course> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course model instance should use the {@link Course} interface instead.
	 */

	/**
	 * Returns the primary key of this course.
	 *
	 * @return the primary key of this course
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course.
	 *
	 * @param primaryKey the primary key of this course
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the course ID of this course.
	 *
	 * @return the course ID of this course
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course.
	 *
	 * @param courseId the course ID of this course
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the course name of this course.
	 *
	 * @return the course name of this course
	 */
	@AutoEscape
	public String getCourseName();

	/**
	 * Sets the course name of this course.
	 *
	 * @param courseName the course name of this course
	 */
	public void setCourseName(String courseName);

	/**
	 * Returns the description of this course.
	 *
	 * @return the description of this course
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this course.
	 *
	 * @param description the description of this course
	 */
	public void setDescription(String description);

	/**
	 * Returns the credits of this course.
	 *
	 * @return the credits of this course
	 */
	public int getCredits();

	/**
	 * Sets the credits of this course.
	 *
	 * @param credits the credits of this course
	 */
	public void setCredits(int credits);

	/**
	 * Returns the students of this course.
	 *
	 * @return the students of this course
	 */
	public int getStudents();

	/**
	 * Sets the students of this course.
	 *
	 * @param students the students of this course
	 */
	public void setStudents(int students);

	@Override
	public Course cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}